version: "3"
services:
  client:
    image: "skillboost/multi-client"
    mem_limit: 128m
    # accessibility for this group of services
    # to this container by "ID" set in "hostname"
    # if it would be specified as "google.com"
    # from one of the containers it would be
    # redirected to this container
    # optional: has to be set only if other
    # container are trying to reach for this one
    hostname: client
  server:
    image: "skillboost/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "skillboost/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "skillboost/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"